### ISSUE TITLE
Clarification between Academics and Opportunities in regards to VIP

### ISSUE THREAD

**Issue by sachiniyer** [BUGS-NYU/nyu-cs-wiki#63]
I am unclear on why the VIP section is notated underneath the Academics tab? To me it seems like it would be best fit underneath NYU Internal underneath the Opportunities tab.

**Comment by aminoa** [comment]
Originally, I was unsure since depending on the VIP, it may have more of an academic. research or simply swe angle to it. I didn't have a preference and in the last PR it moved locations. However, NYU specifically does consider VIPs as a part of student research (https://engineering.nyu.edu/research-innovation/student-research) so I'll move it back.

**Comment by aminoa** [comment]
I'll put it in its own section now since there will be multiple articles there (rather than just giving an overview of VIPs).
